from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from split_stack.discovery import discover_models
from split_stack.model_registry import normalize_deployment_profile
from split_stack.presets import RECOMMENDED_STACKS, assign_recommended_tiers, list_recommended_stacks, recommended_models
from split_stack.tiering import describe_tiers


@dataclass(frozen=True)
class SetupPlan:
    profile: str
    description: str
    models: tuple[str, ...]
    installed: tuple[str, ...]
    missing: tuple[str, ...]
    config_path: Path


@dataclass(frozen=True)
class SetupResult:
    profile: str
    config_path: Path
    pulled: tuple[str, ...]
    skipped: tuple[str, ...]
    already_present: tuple[str, ...]
    tiers: dict[str, str | None]
    cancelled: bool = False
    dry_run: bool = False
    error: str | None = None

    @property
    def ready(self) -> bool:
        return self.error is None and not self.cancelled


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def default_config_path() -> Path:
    return Path.cwd() / "split-stack.models.json"


def model_is_installed(tag: str, installed: list[str]) -> bool:
    wanted = tag.lower()
    for name in installed:
        lowered = name.lower()
        if lowered == wanted or lowered.startswith(f"{wanted}:"):
            return True
        if wanted in lowered and ":" in wanted:
            return True
    return False


def plan_setup(
    profile: str,
    *,
    base_url: str = "http://127.0.0.1:11434",
    config_path: Path | None = None,
) -> SetupPlan:
    profile_name = normalize_deployment_profile(profile)
    stack = RECOMMENDED_STACKS[profile_name]
    installed = discover_models(base_url=base_url)
    missing = [tag for tag in stack.models if not model_is_installed(tag, installed)]
    present = [tag for tag in stack.models if model_is_installed(tag, installed)]
    return SetupPlan(
        profile=profile_name,
        description=stack.description,
        models=stack.models,
        installed=tuple(present),
        missing=tuple(missing),
        config_path=config_path or default_config_path(),
    )


def pull_model(
    tag: str,
    *,
    base_url: str = "http://127.0.0.1:11434",
    timeout_seconds: int = 3600,
) -> None:
    try:
        import requests
    except ImportError as exc:
        raise RuntimeError(
            "pull_model requires optional dependency: pip install split-stack[ollama]"
        ) from exc

    response = requests.post(
        f"{base_url.rstrip('/')}/api/pull",
        json={"name": tag, "stream": False},
        timeout=timeout_seconds,
    )
    response.raise_for_status()


def write_setup_config(profile: str, config_path: Path) -> None:
    profile_name = normalize_deployment_profile(profile)
    template_path = _repo_root() / "config" / "models.example.json"
    if template_path.is_file():
        payload = json.loads(template_path.read_text(encoding="utf-8"))
    else:
        payload = {"models": []}
    payload["deployment_profile"] = profile_name
    payload["comment"] = f"Generated by stack setup ({profile_name}). Edit models[] if your tags differ."
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def prompt_profile_choice() -> str:
    stacks = list_recommended_stacks()
    print("Choose your GPU preset:")
    for index, stack in enumerate(stacks, start=1):
        print(f"  {index}. {stack.profile} — {stack.description}")
    print("")
    while True:
        raw = input(f"Preset [1-{len(stacks)}] (default 2 = workstation_12gb): ").strip()
        if not raw:
            return "workstation_12gb"
        if raw.isdigit():
            choice = int(raw)
            if 1 <= choice <= len(stacks):
                return stacks[choice - 1].profile
        lowered = raw.lower()
        try:
            return normalize_deployment_profile(lowered)
        except ValueError:
            print("Enter a preset number or name like workstation_12gb / 12gb.")


def prompt_download_consent(*, missing: tuple[str, ...]) -> bool:
    if not missing:
        return True
    print("")
    print(f"Ollama will download {len(missing)} model(s) (large files, one-time):")
    for tag in missing:
        print(f"  - {tag}")
    print("")
    answer = input("Proceed with download? [y/N]: ").strip().lower()
    return answer in {"y", "yes"}


def run_setup(
    profile: str | None = None,
    *,
    base_url: str = "http://127.0.0.1:11434",
    config_path: Path | None = None,
    assume_yes: bool = False,
    dry_run: bool = False,
    interactive: bool = True,
) -> SetupResult:
    chosen = profile
    if not chosen and interactive:
        chosen = prompt_profile_choice()
    if not chosen:
        chosen = "workstation_12gb"

    path = config_path or default_config_path()
    try:
        plan = plan_setup(chosen, base_url=base_url, config_path=path)
    except Exception as exc:
        return SetupResult(
            profile=chosen,
            config_path=path,
            pulled=(),
            skipped=(),
            already_present=(),
            tiers={},
            error=str(exc),
        )

    if dry_run:
        tiers = describe_tiers(assign_recommended_tiers(plan.profile))
        return SetupResult(
            profile=plan.profile,
            config_path=plan.config_path,
            pulled=(),
            skipped=plan.missing,
            already_present=plan.installed,
            tiers=tiers,
            dry_run=True,
        )

    if plan.missing and not assume_yes and interactive:
        if not prompt_download_consent(missing=plan.missing):
            return SetupResult(
                profile=plan.profile,
                config_path=plan.config_path,
                pulled=(),
                skipped=plan.missing,
                already_present=plan.installed,
                tiers={},
                cancelled=True,
            )

    pulled: list[str] = []
    errors: list[str] = []
    for tag in plan.missing:
        try:
            print(f"Pulling {tag}...", flush=True)
            pull_model(tag, base_url=base_url)
            pulled.append(tag)
        except Exception as exc:
            errors.append(f"{tag}: {exc}")

    try:
        write_setup_config(plan.profile, plan.config_path)
        tiers = describe_tiers(assign_recommended_tiers(plan.profile))
    except Exception as exc:
        errors.append(str(exc))
        tiers = {}

    if errors:
        return SetupResult(
            profile=plan.profile,
            config_path=plan.config_path,
            pulled=tuple(pulled),
            skipped=tuple([tag for tag in plan.missing if tag not in pulled]),
            already_present=plan.installed,
            tiers=tiers,
            error="; ".join(errors),
        )

    return SetupResult(
        profile=plan.profile,
        config_path=plan.config_path,
        pulled=tuple(pulled),
        skipped=(),
        already_present=plan.installed,
        tiers=tiers,
    )


def format_setup_summary(result: SetupResult) -> str:
    lines = [
        f"profile={result.profile}",
        f"config={result.config_path}",
    ]
    if result.already_present:
        lines.append(f"already_present={','.join(result.already_present)}")
    if result.pulled:
        lines.append(f"pulled={','.join(result.pulled)}")
    if result.skipped:
        lines.append(f"not_installed={','.join(result.skipped)}")
    if result.tiers:
        lines.append("tiers:")
        for key, value in result.tiers.items():
            lines.append(f"  {key}: {value or '-'}")
    if result.cancelled:
        lines.append("status=cancelled (no downloads)")
    if result.dry_run:
        lines.append("status=dry-run")
    if result.error:
        lines.append(f"error={result.error}")
    return "\n".join(lines)
